org-formation/aws-resource-providers

- common/README.md
- common/package-lock.json
- common/package.json
- common/src/common-decorator.ts
Support for logger proxy in common library as well as updating dependencies to point to NPM.
> Support for logger proxy in common lib

- common/__tests__/common-decorator.test.ts
- common/jest.config.js
- common/package-lock.json
- common/package.json
- common/src/common-decorator.ts
Support service constructor option in common AWS decorator
> feat(aws-resource-providers-common): support service constructor option

- iam/password-policy/README.md
> docs(community-iam-passwordpolicy): fix documentation

- ec2/no-default-vpc/installation.md
The installation docs are slightly incorrect, just needed
a little update.
> docs(community-organizations-nodefaultvpc): Fix documentation

- cloud-formation/delay/package.json
- code-commit/approval-rule-template/package.json
- code-commit/repository-association/package.json
- ec2/ebs-encryption-defaults/package.json
- ec2/no-default-vpc/package.json
- iam/oidc-providers/package.json
- iam/password-policy/package.json
- iam/saml-provider/package.json
- organizations/policy/package.json
- s3/public-access-block/package.json
- s3/public-access-block/src/handlers.ts
- service-quotas/cloud-formation/package.json
- service-quotas/s3/package.json
- sso/assignment-group/package.json
> feat: move resoure roles to /community-types/

- ec2/no-default-vpc/installation.md
- s3/public-access-block/installation.md
- s3/public-access-block/package.json
- s3/public-access-block/resource-role.yaml
- s3/public-access-block/src/handlers.ts
putPublicAccessBlock failed previously because serialize() method returned things like 'ResourceId' and apparently not all values had the right type...
> fix(s3-public-access-block): fixed upset handler that failed because invalid arguments

- ec2/no-default-vpc/installation.md
*Description of changes:* Update title to reflect current resource
> Update title to reflect current resource

- organizations/policy/community-organizations-policy.json
- organizations/policy/package.json
> fix: updated org policy replacement strategy

- .github/workflows/cicd.yml
https://github.com/aws/aws-sam-cli/issues/1424
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html
> ci: install aws-sam-cli without pip

- .github/workflows/cicd.yml
introduced in https://github.com/org-formation/aws-resource-providers/pull/90, this gets the build a bit further along
> ci: sam-install in separate directory

- .github/workflows/cicd.yml
- account/alternate-contact/.npmrc
- common/__tests__/common-decorator.test.ts
- common/package-lock.json
- common/package.json
- common/src/common-decorator.ts
- common/src/service-quotas.ts
- package-lock.json
- package.json
- route53/vpc-association-authorization/.npmrc
- route53/vpc-association/.npmrc
- service-quotas/iam/.npmrc
- ssm/public-access-block/.npmrc
Use v1.0.1 of cfn-rpdk from AWS.
> feat(common): use latest cfn-rpdk in common lib

- security-hub/standards-control/.npmrc
- security-hub/standards-control/.rpdk-config
- security-hub/standards-control/README.md
- security-hub/standards-control/community-securityhub-standardscontrol.json
- security-hub/standards-control/docs/README.md
- security-hub/standards-control/example.yml
- security-hub/standards-control/jest.config.js
- security-hub/standards-control/package-lock.json
- security-hub/standards-control/package.json
- security-hub/standards-control/resource-role.yaml
- security-hub/standards-control/src/handlers.ts
- security-hub/standards-control/src/models.ts
- security-hub/standards-control/template.yml
- security-hub/standards-control/tsconfig.json
> feat: security hub standards control

- detective/management/.gitignore
- detective/management/.npmrc
- detective/management/.rpdk-config
- detective/management/README.md
- detective/management/community-detective-management.json
- detective/management/docs/README.md
- detective/management/example_inputs/inputs_1_create.json
- detective/management/example_inputs/inputs_1_invalid.json
- detective/management/example_inputs/inputs_1_update.json
- detective/management/package-lock.json
- detective/management/package.json
- detective/management/resource-role.yaml
- detective/management/src/handlers.ts
- detective/management/src/models.ts
- detective/management/template.yml
- detective/management/tsconfig.json
> feat: aws detective management resource

- security-hub/hub/.gitignore
- security-hub/hub/.npmrc
- security-hub/hub/.rpdk-config
- security-hub/hub/README.md
- security-hub/hub/community-securityhub-hub.json
- security-hub/hub/docs/README.md
- security-hub/hub/example_inputs/inputs_1_create.json
- security-hub/hub/example_inputs/inputs_1_invalid.json
- security-hub/hub/example_inputs/inputs_1_update.json
- security-hub/hub/package-lock.json
- security-hub/hub/package.json
- security-hub/hub/resource-role.yaml
- security-hub/hub/src/handlers.ts
- security-hub/hub/src/models.ts
- security-hub/hub/template.yml
- security-hub/hub/tsconfig.json
> feat: security-hub hub resource

- direct-connect/gateway/.gitignore
- direct-connect/gateway/.npmrc
- direct-connect/gateway/.rpdk-config
- direct-connect/gateway/README.md
- direct-connect/gateway/community-directconnect-gateway.json
- direct-connect/gateway/docs/README.md
- direct-connect/gateway/jest.config.js
- direct-connect/gateway/package-lock.json
- direct-connect/gateway/package.json
- direct-connect/gateway/resource-role.yaml
- direct-connect/gateway/src/handlers.ts
- direct-connect/gateway/src/models.ts
- direct-connect/gateway/template.yml
- direct-connect/gateway/test/data/create-success.json
- direct-connect/gateway/test/data/delete-success.json
- direct-connect/gateway/test/data/read-success.json
- direct-connect/gateway/test/data/update-success.json
- direct-connect/gateway/test/handlers.test.ts
- direct-connect/gateway/tsconfig.eslint.json
- direct-connect/gateway/tsconfig.json
> feat: add Community::DirectConnect::Gateway

- direct-connect/transit-virtual-interface/.gitignore
- direct-connect/transit-virtual-interface/.npmrc
- direct-connect/transit-virtual-interface/.rpdk-config
- direct-connect/transit-virtual-interface/README.md
- direct-connect/transit-virtual-interface/community-directconnect-transitvirtualinterface.json
- direct-connect/transit-virtual-interface/docs/README.md
- direct-connect/transit-virtual-interface/docs/tag.md
- direct-connect/transit-virtual-interface/jest.config.js
- direct-connect/transit-virtual-interface/junit.xml
- direct-connect/transit-virtual-interface/package-lock.json
- direct-connect/transit-virtual-interface/package.json
- direct-connect/transit-virtual-interface/resource-role.yaml
- direct-connect/transit-virtual-interface/src/handlers.ts
- direct-connect/transit-virtual-interface/src/models.ts
- direct-connect/transit-virtual-interface/template.yml
- direct-connect/transit-virtual-interface/test/data/create-success.json
- direct-connect/transit-virtual-interface/test/data/delete-success.json
- direct-connect/transit-virtual-interface/test/data/read-success.json
- direct-connect/transit-virtual-interface/test/data/update-success.json
- direct-connect/transit-virtual-interface/test/handlers.test.ts
- direct-connect/transit-virtual-interface/tsconfig.eslint.json
- direct-connect/transit-virtual-interface/tsconfig.json
> Implement Community::DirectConnect::TransitVirtualInterface

- security-hub/hub/community-securityhub-hub.json
- security-hub/hub/docs/README.md
- security-hub/hub/package-lock.json
- security-hub/hub/package.json
- security-hub/hub/src/handlers.ts
- security-hub/hub/src/models.ts
support consolidated findings, example:
```
Hub:
Type: Community::SecurityHub::Hub
Properties:
EnableDefaultStandards: false
ControlFindingGenerator: SECURITY_CONTROL # enables consolidated findings, STANDARD_CONTROL does not (default)
```
released as: `s3://community-resource-provider-catalog/community-securityhub-hub-0.1.3.zip`
> feat: support consolidated findings on hub

- security-hub/finding-aggregation/.gitignore
- security-hub/finding-aggregation/.npmrc
- security-hub/finding-aggregation/.rpdk-config
- security-hub/finding-aggregation/README.md
- security-hub/finding-aggregation/community-securityhub-findingaggregation.json
- security-hub/finding-aggregation/docs/README.md
- security-hub/finding-aggregation/example_inputs/inputs_1_create.json
- security-hub/finding-aggregation/example_inputs/inputs_1_invalid.json
- security-hub/finding-aggregation/example_inputs/inputs_1_update.json
- security-hub/finding-aggregation/package-lock.json
- security-hub/finding-aggregation/package.json
- security-hub/finding-aggregation/resource-role.yaml
- security-hub/finding-aggregation/src/handlers.ts
- security-hub/finding-aggregation/src/models.ts
- security-hub/finding-aggregation/template.yml
- security-hub/finding-aggregation/tsconfig.json
resource to set up security hub finding aggregation:
```
FindingAggregation:
Type: Community::SecurityHub::FindingAggregation
Properties:
RegionLinkingMode: SPECIFIED_REGIONS
Regions: 
- eu-central-1
````
published as: `s3://community-resource-provider-catalog/community-securityhub-findingaggregation-0.1.0.zip`
> feat: Community::SecurityHub::FindingAggregation

- security-hub/standards/docs/README.md
- security-hub/standards/src/handlers.ts
- security-hub/standards/src/models.ts
*Issue #, if available:* No issue created
*Description of changes:* This PR aims to support *NIST Special Publication 800-53 Revision 5* standard
> feat: Community::SecurityHub::Standards add nist 800-53 v5 revision support

- common/package-lock.json
- common/package.json
- common/src/common-decorator.ts
- support/support-level/src/handlers.ts
> feat: allow type configuration to be consumed via the decorator

- security-hub/finding-aggregation/community-securityhub-findingaggregation.json
- security-hub/finding-aggregation/package-lock.json
- security-hub/finding-aggregation/package.json
- security-hub/finding-aggregation/resource-role.yaml
> fix: delete aggregator permission missing from manifest

- organizations/enable-aws-service/community-organizations-enableawsserviceaccess.json
- security-hub/members/community-securityhub-members.json
- security-hub/members/package-lock.json
- security-hub/members/package.json
- security-hub/members/resource-role.yaml
- security-hub/members/src/handlers.ts
- security-hub/security-control/.npmrc
- security-hub/security-control/.rpdk-config
- security-hub/security-control/README.md
- security-hub/security-control/community-securityhub-securitycontrol.json
- security-hub/security-control/docs/README.md
- security-hub/security-control/example.yml
- security-hub/security-control/jest.config.js
- security-hub/security-control/package-lock.json
- security-hub/security-control/package.json
- security-hub/security-control/resource-role.yaml
- security-hub/security-control/src/handlers.ts
- security-hub/security-control/src/models.ts
- security-hub/security-control/template.yml
- security-hub/security-control/tsconfig.json
support a large number of members in securityhub by batching member invites
> feat: batched members

- organizations/enable-aws-service/community-organizations-enableawsserviceaccess.json
- security-hub/security-control/.npmrc
- security-hub/security-control/.rpdk-config
- security-hub/security-control/README.md
- security-hub/security-control/community-securityhub-securitycontrol.json
- security-hub/security-control/docs/README.md
- security-hub/security-control/example.yml
- security-hub/security-control/jest.config.js
- security-hub/security-control/package-lock.json
- security-hub/security-control/package.json
- security-hub/security-control/resource-role.yaml
- security-hub/security-control/src/handlers.ts
- security-hub/security-control/src/models.ts
- security-hub/security-control/template.yml
- security-hub/security-control/tsconfig.json
> feat: securityhub security control

- security-hub/members/package-lock.json
- security-hub/members/package.json
- security-hub/members/src/handlers.ts
> chore: page over list members

- code-commit/approval-rule-template/installation.md
- code-commit/repository-association/installation.md
> chore: update installation.md files

- network-manager/accept-attachment/.gitignore
- network-manager/accept-attachment/.npmrc
- network-manager/accept-attachment/.rpdk-config
- network-manager/accept-attachment/README.md
- network-manager/accept-attachment/community-networkmanager-acceptattachment.json
- network-manager/accept-attachment/docs/README.md
- network-manager/accept-attachment/jest.config.js
- network-manager/accept-attachment/junit.xml
- network-manager/accept-attachment/package-lock.json
- network-manager/accept-attachment/package.json
- network-manager/accept-attachment/resource-role.yaml
- network-manager/accept-attachment/src/handlers.ts
- network-manager/accept-attachment/src/models.ts
- network-manager/accept-attachment/template.yml
- network-manager/accept-attachment/test/fixtures/create_success.json
- network-manager/accept-attachment/test/fixtures/read_vpc_success.json
- network-manager/accept-attachment/test/handlers.test.ts
- network-manager/accept-attachment/tsconfig.eslint.json
- network-manager/accept-attachment/tsconfig.json
Adding a new resource Community::NetworkManager::AcceptAttachment which allows acceptance of pending core network attachments from the core network owner account.
> Add Community::NetworkManager::AcceptAttachment

- sso/assignment-group/package.json
- sso/assignment-group/resource-role.yaml
- sso/assignment-group/src/models.ts
> chore: update assignment group

- sso/assignment-group/community-sso-assignmentgroup.json
- sso/assignment-group/package.json
closes: #143
versioned as 1.0.1
uploaded to: s3://community-resource-provider-catalog/community-sso-assignmentgroup-1.0.1.zip
thanks @logicata-jon!
> fix: sso assignment group permissions

- ec2/instance-metadata-defaults/.gitignore
- ec2/instance-metadata-defaults/.npmrc
- ec2/instance-metadata-defaults/.rpdk-config
- ec2/instance-metadata-defaults/README.md
- ec2/instance-metadata-defaults/community-organizations-instancemetadatadefaults.json
- ec2/instance-metadata-defaults/example.yml
- ec2/instance-metadata-defaults/package-lock.json
- ec2/instance-metadata-defaults/package.json
- ec2/instance-metadata-defaults/resource-role.yaml
- ec2/instance-metadata-defaults/src/handlers.ts
- ec2/instance-metadata-defaults/src/models.ts
- ec2/instance-metadata-defaults/template.yml
- ec2/instance-metadata-defaults/tsconfig.json
- fms/admin-account/.gitignore
- fms/admin-account/.npmrc
- fms/admin-account/.rpdk-config
- fms/admin-account/README.md
- fms/admin-account/community-fms-adminaccount.json
- fms/admin-account/docs/README.md
- fms/admin-account/example_inputs/inputs_1_create.json
- fms/admin-account/example_inputs/inputs_1_invalid.json
- fms/admin-account/example_inputs/inputs_1_update.json
- fms/admin-account/package-lock.json
- fms/admin-account/package.json
- fms/admin-account/resource-role.yaml
- fms/admin-account/src/handlers.ts
- fms/admin-account/src/models.ts
- fms/admin-account/template.yml
- fms/admin-account/tsconfig.json
> feat: ec2-instance-metadata-defaults
